<?php

/**
 * BaseTutorQuiz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $tutor_id
 * @property integer $quiz_id
 * @property Tutor $tutor
 * @property Quiz $quiz
 * 
 * @method integer   getTutorId()  Returns the current record's "tutor_id" value
 * @method integer   getQuizId()   Returns the current record's "quiz_id" value
 * @method Tutor     getTutor()    Returns the current record's "tutor" value
 * @method Quiz      getQuiz()     Returns the current record's "quiz" value
 * @method TutorQuiz setTutorId()  Sets the current record's "tutor_id" value
 * @method TutorQuiz setQuizId()   Sets the current record's "quiz_id" value
 * @method TutorQuiz setTutor()    Sets the current record's "tutor" value
 * @method TutorQuiz setQuiz()     Sets the current record's "quiz" value
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto@webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTutorQuiz extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tutor_quiz');
        $this->hasColumn('tutor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('quiz_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('tutor_quiz_index', array(
             'fields' => 
             array(
              0 => 'tutor_id',
              1 => 'quiz_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Tutor as tutor', array(
             'local' => 'tutor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Quiz as quiz', array(
             'local' => 'quiz_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}