<?php

/**
 * BaseTutor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property text $apellido
 * @property text $email
 * @property Doctrine_Collection $Grupo
 * @property Doctrine_Collection $TutorQuiz
 * 
 * @method text                getNombre()    Returns the current record's "nombre" value
 * @method text                getApellido()  Returns the current record's "apellido" value
 * @method text                getEmail()     Returns the current record's "email" value
 * @method Doctrine_Collection getGrupo()     Returns the current record's "Grupo" collection
 * @method Doctrine_Collection getTutorQuiz() Returns the current record's "TutorQuiz" collection
 * @method Tutor               setNombre()    Sets the current record's "nombre" value
 * @method Tutor               setApellido()  Sets the current record's "apellido" value
 * @method Tutor               setEmail()     Sets the current record's "email" value
 * @method Tutor               setGrupo()     Sets the current record's "Grupo" collection
 * @method Tutor               setTutorQuiz() Sets the current record's "TutorQuiz" collection
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTutor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tutor');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('apellido', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('email', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Grupo', array(
             'local' => 'id',
             'foreign' => 'tutor_id'));

        $this->hasMany('TutorQuiz', array(
             'local' => 'id',
             'foreign' => 'tutor_id'));
    }
}