<?php

/**
 * BaseAlumno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property text $apellido
 * @property varchar $matricula
 * @property text $carrera
 * @property integer $grupo_id
 * @property Grupo $Grupo
 * @property Doctrine_Collection $AlumnoQuiz
 * 
 * @method text                getNombre()     Returns the current record's "nombre" value
 * @method text                getApellido()   Returns the current record's "apellido" value
 * @method varchar             getMatricula()  Returns the current record's "matricula" value
 * @method text                getCarrera()    Returns the current record's "carrera" value
 * @method integer             getGrupoId()    Returns the current record's "grupo_id" value
 * @method Grupo               getGrupo()      Returns the current record's "Grupo" value
 * @method Doctrine_Collection getAlumnoQuiz() Returns the current record's "AlumnoQuiz" collection
 * @method Alumno              setNombre()     Sets the current record's "nombre" value
 * @method Alumno              setApellido()   Sets the current record's "apellido" value
 * @method Alumno              setMatricula()  Sets the current record's "matricula" value
 * @method Alumno              setCarrera()    Sets the current record's "carrera" value
 * @method Alumno              setGrupoId()    Sets the current record's "grupo_id" value
 * @method Alumno              setGrupo()      Sets the current record's "Grupo" value
 * @method Alumno              setAlumnoQuiz() Sets the current record's "AlumnoQuiz" collection
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlumno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alumno');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('apellido', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('matricula', 'varchar', 10, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('carrera', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('grupo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grupo', array(
             'local' => 'grupo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('AlumnoQuiz', array(
             'local' => 'id',
             'foreign' => 'alumno_id'));
    }
}