<?php

/**
 * BaseGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property integer $modulo_id
 * @property integer $tutor_id
 * @property Modulo $Modulo
 * @property Tutor $Tutor
 * @property Doctrine_Collection $Alumno
 * 
 * @method text                getNombre()    Returns the current record's "nombre" value
 * @method integer             getModuloId()  Returns the current record's "modulo_id" value
 * @method integer             getTutorId()   Returns the current record's "tutor_id" value
 * @method Modulo              getModulo()    Returns the current record's "Modulo" value
 * @method Tutor               getTutor()     Returns the current record's "Tutor" value
 * @method Doctrine_Collection getAlumno()    Returns the current record's "Alumno" collection
 * @method Grupo               setNombre()    Sets the current record's "nombre" value
 * @method Grupo               setModuloId()  Sets the current record's "modulo_id" value
 * @method Grupo               setTutorId()   Sets the current record's "tutor_id" value
 * @method Grupo               setModulo()    Sets the current record's "Modulo" value
 * @method Grupo               setTutor()     Sets the current record's "Tutor" value
 * @method Grupo               setAlumno()    Sets the current record's "Alumno" collection
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto@webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('modulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tutor_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Modulo', array(
             'local' => 'modulo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Tutor', array(
             'local' => 'tutor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Alumno', array(
             'local' => 'id',
             'foreign' => 'grupo_id'));
    }
}