<?php

/**
 * BaseLaboratorioQuiz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $laboratorio_id
 * @property integer $quiz_id
 * @property Laboratorio $laboratorio
 * @property Quiz $quiz
 * 
 * @method integer         getLaboratorioId()  Returns the current record's "laboratorio_id" value
 * @method integer         getQuizId()         Returns the current record's "quiz_id" value
 * @method Laboratorio     getLaboratorio()    Returns the current record's "laboratorio" value
 * @method Quiz            getQuiz()           Returns the current record's "quiz" value
 * @method LaboratorioQuiz setLaboratorioId()  Sets the current record's "laboratorio_id" value
 * @method LaboratorioQuiz setQuizId()         Sets the current record's "quiz_id" value
 * @method LaboratorioQuiz setLaboratorio()    Sets the current record's "laboratorio" value
 * @method LaboratorioQuiz setQuiz()           Sets the current record's "quiz" value
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto@webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLaboratorioQuiz extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('laboratorio_quiz');
        $this->hasColumn('laboratorio_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('quiz_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('laboratorio_quiz_index', array(
             'fields' => 
             array(
              0 => 'laboratorio_id',
              1 => 'quiz_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Laboratorio as laboratorio', array(
             'local' => 'laboratorio_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Quiz as quiz', array(
             'local' => 'quiz_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}