<?php

/**
 * BaseAlumnoQuiz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $alumno_id
 * @property integer $quiz_id
 * @property Alumno $alumno
 * @property Quiz $quiz
 * 
 * @method integer    getAlumnoId()  Returns the current record's "alumno_id" value
 * @method integer    getQuizId()    Returns the current record's "quiz_id" value
 * @method Alumno     getAlumno()    Returns the current record's "alumno" value
 * @method Quiz       getQuiz()      Returns the current record's "quiz" value
 * @method AlumnoQuiz setAlumnoId()  Sets the current record's "alumno_id" value
 * @method AlumnoQuiz setQuizId()    Sets the current record's "quiz_id" value
 * @method AlumnoQuiz setAlumno()    Sets the current record's "alumno" value
 * @method AlumnoQuiz setQuiz()      Sets the current record's "quiz" value
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlumnoQuiz extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alumno_quiz');
        $this->hasColumn('alumno_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('quiz_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('alumno_quiz_index', array(
             'fields' => 
             array(
              0 => 'alumno_id',
              1 => 'quiz_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Alumno as alumno', array(
             'local' => 'alumno_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Quiz as quiz', array(
             'local' => 'quiz_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}