<?php

/**
 * BaseCarrera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * 
 * @method text    getNombre() Returns the current record's "nombre" value
 * @method Carrera setNombre() Sets the current record's "nombre" value
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto@webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarrera extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carrera');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}