<?php

/**
 * BaseQuiz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha_at
 * @property time $hora_ini
 * @property time $hora_fin
 * @property integer $cupo
 * @property integer $lesson_id
 * @property Lesson $Lesson
 * @property Doctrine_Collection $TutorQuiz
 * @property Doctrine_Collection $AlumnoQuiz
 * @property Doctrine_Collection $LaboratorioQuiz
 * 
 * @method date                getFechaAt()         Returns the current record's "fecha_at" value
 * @method time                getHoraIni()         Returns the current record's "hora_ini" value
 * @method time                getHoraFin()         Returns the current record's "hora_fin" value
 * @method integer             getCupo()            Returns the current record's "cupo" value
 * @method integer             getLessonId()        Returns the current record's "lesson_id" value
 * @method Lesson              getLesson()          Returns the current record's "Lesson" value
 * @method Doctrine_Collection getTutorQuiz()       Returns the current record's "TutorQuiz" collection
 * @method Doctrine_Collection getAlumnoQuiz()      Returns the current record's "AlumnoQuiz" collection
 * @method Doctrine_Collection getLaboratorioQuiz() Returns the current record's "LaboratorioQuiz" collection
 * @method Quiz                setFechaAt()         Sets the current record's "fecha_at" value
 * @method Quiz                setHoraIni()         Sets the current record's "hora_ini" value
 * @method Quiz                setHoraFin()         Sets the current record's "hora_fin" value
 * @method Quiz                setCupo()            Sets the current record's "cupo" value
 * @method Quiz                setLessonId()        Sets the current record's "lesson_id" value
 * @method Quiz                setLesson()          Sets the current record's "Lesson" value
 * @method Quiz                setTutorQuiz()       Sets the current record's "TutorQuiz" collection
 * @method Quiz                setAlumnoQuiz()      Sets the current record's "AlumnoQuiz" collection
 * @method Quiz                setLaboratorioQuiz() Sets the current record's "LaboratorioQuiz" collection
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto@webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuiz extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quiz');
        $this->hasColumn('fecha_at', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hora_ini', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('hora_fin', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('cupo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lesson_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Lesson', array(
             'local' => 'lesson_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('TutorQuiz', array(
             'local' => 'id',
             'foreign' => 'quiz_id'));

        $this->hasMany('AlumnoQuiz', array(
             'local' => 'id',
             'foreign' => 'quiz_id'));

        $this->hasMany('LaboratorioQuiz', array(
             'local' => 'id',
             'foreign' => 'quiz_id'));
    }
}