<?php

/**
 * BaseAlumno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $carrera_id
 * @property varchar $matricula
 * @property integer $grupo_id
 * @property sfGuardUser $sfGuardUser
 * @property Grupo $Grupo
 * @property Carrera $Carrera
 * @property Doctrine_Collection $AlumnoQuiz
 * 
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getCarreraId()   Returns the current record's "carrera_id" value
 * @method varchar             getMatricula()   Returns the current record's "matricula" value
 * @method integer             getGrupoId()     Returns the current record's "grupo_id" value
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Grupo               getGrupo()       Returns the current record's "Grupo" value
 * @method Carrera             getCarrera()     Returns the current record's "Carrera" value
 * @method Doctrine_Collection getAlumnoQuiz()  Returns the current record's "AlumnoQuiz" collection
 * @method Alumno              setUserId()      Sets the current record's "user_id" value
 * @method Alumno              setCarreraId()   Sets the current record's "carrera_id" value
 * @method Alumno              setMatricula()   Sets the current record's "matricula" value
 * @method Alumno              setGrupoId()     Sets the current record's "grupo_id" value
 * @method Alumno              setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Alumno              setGrupo()       Sets the current record's "Grupo" value
 * @method Alumno              setCarrera()     Sets the current record's "Carrera" value
 * @method Alumno              setAlumnoQuiz()  Sets the current record's "AlumnoQuiz" collection
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto@webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlumno extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alumno');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('carrera_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('matricula', 'varchar', 10, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('grupo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Grupo', array(
             'local' => 'grupo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Carrera', array(
             'local' => 'carrera_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('AlumnoQuiz', array(
             'local' => 'id',
             'foreign' => 'alumno_id'));
    }
}