<?php

/**
 * BaseCarrera
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $nombre
 * @property Doctrine_Collection $Alumno
 * 
 * @method text                getNombre() Returns the current record's "nombre" value
 * @method Doctrine_Collection getAlumno() Returns the current record's "Alumno" collection
 * @method Carrera             setNombre() Sets the current record's "nombre" value
 * @method Carrera             setAlumno() Sets the current record's "Alumno" collection
 * 
 * @package    quizsignup
 * @subpackage model
 * @author     Rodrigo Campos H. <contacto@webdevel.cl>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarrera extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carrera');
        $this->hasColumn('nombre', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Alumno', array(
             'local' => 'id',
             'foreign' => 'carrera_id'));
    }
}