# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        QuizSignUp - Admin Panel
    #description:  symfony project
    #keywords:     symfony, project
    language:     es
    #robots:       index, follow

  stylesheets:
    - style.css
    - fixed.css

  javascripts:
    - excanvas.min.js
    - jquery-1.6.1.min.js
    - jquery-1.3.2.min.js
    - jquery.dataTables.min.js
    - jquery.labelify.js
    - jquery-ui-1.8.14.custom.min.js
    - iphone-style-checkboxes.js
#    - jquery.ui.selectmenu.js
#    - vanadium-min.js
#    - jquery.cleditor.min.js
#    - jquery.flot.min.js
#    - jquery.flot.pie.min.js
#    - jquery.flot.stack.min.js
    - superfish.js
#    - jquery.colorbox-min.js
#    - styleswitch.js
#    - fullcalendar.min.js
#    - jquery.uploadify.v2.1.4.min.js
#    - uploadify.js
#    - jquery.tipsy.js
#    - gcal.js
#    - swfobject.js
    - examples.js
    - html5.js: { condition: IE 9 }
    - IE7.css: { condition: IE 7 }

  has_layout:     true
  layout:         layout
