<?php

/**
 * AlumnoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlumnoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlumnoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Alumno');
    }
}