<?php

/**
 * AlumnoQuizTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlumnoQuizTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlumnoQuizTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlumnoQuiz');
    }
}