<?php

/**
 * LaboratorioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LaboratorioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LaboratorioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Laboratorio');
    }
}