<?php

/**
 * TutorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TutorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TutorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tutor');
    }
}