<?php

/**
 * TutorQuizTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TutorQuizTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TutorQuizTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TutorQuiz');
    }
}